name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s --health-timeout 3s --health-retries 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip && pip install -r requirements.txt
      - name: Lint
        run: |
          pip install ruff black
          ruff check .
          black --check .
      - name: Smoke Test
        env:
          JWT_SECRET: test_secret
          REDIS_URL: redis://localhost:6379
          DATABASE_URL: sqlite:///./im.db
        run: |
          python - <<'PY'
          from fastapi.testclient import TestClient
          from main import app
          c = TestClient(app)
          r = c.get('/health')
          assert r.status_code == 200
          print('health ok')
          PY

